### PR TITLE
Format errors and add authentication in GraphQL

### LINKED ISSUE #17: Avoid bubbling typeorm details through errors to consumers
Right now, if you encounter any kind of typeorm error (validation, conflict, etc) that bubbles in an exception it will be exposed completely to consumers.

We need to handle those errors in a way that works (ideally universally) to hide the internals of the system from consumers, and bubble semantically meaningful error messages instead.

Sidenote: we also may want to adopt something akin to our REST endpoints' `expose` property on errors, which will only expose errors that should be exposed (i.e. 4xx errors) to consumers.

### PR DESCRIPTION
**Pull request by mshwery**
This PR adds authentication to the GraphQL schema and enhances error handling with apollo's `formatError`.

This allows us to continue using http-errors and a special `ValidationError` class that extends `class-validator` properties.

Closes #17

### CODE REVIEW

File: app/middleware/errors.ts [hunk 1]
```diff
@@ -13,7 +13,7 @@ export default function handleErrorResponse(error: IError, _req: Request, res: R
   const status = error.status || 500
   let message = 'Server Error'
 
-  if (typeof error.expose !== 'boolean' || error.expose) {
+  if (error.expose) {
```
Comment (mshwery) [inline app/middleware/errors.ts]: Changed this to make it "deny by default"

File: app/graphql/formatError.ts [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+    case 404:
+      return 'NOT_FOUND'
+    case 409:
+      return 'CONFLICT'
+    default:
+      return undefined
+  }
+}
+
+export default function formatError(error): Error {
```
Comment (mshwery) [inline app/graphql/formatError.ts]: TODO: tests for this fn
